nameOverride: coor-test
containerName: coor-test

replicaCount: 1

image:
  repository: 192.168.0.43:5000/cooragent/cooragent
  tag: v2
  pullPolicy: IfNotPresent

imagePullSecrets:
  - barbor

envFromSecret: cooragent-env
env:
  - name: PORT
    value: "18800"

service:
  type: ClusterIP
  name: coor-service
  port: 18800
  targetPort: 18800
  sessionAffinity: None
  clientIPTimeoutSeconds: null

persistence:
  enabled: true
  claimName: cooragent-pvc
  mountPath: /root/.cooragent
